storage = "gs://tufops"          # or gs://bucket/prefix

[keys.arlosi]
owner = "@arlosi"
public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmcIqt4wpIdBCFSZv7EuQkTr7lHjR
kyR5EgRkaB5Am9Zc61orKQc9DiOTs5e9d84px3ebGh1NhzMGBUZHiGB1ow==
-----END PUBLIC KEY-----
"""

[keys.arlosi-backup]
owner = "@arlosi"
public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsB2Hl7venpo7oeAvhyQcEVtl+MzV
WaCZuuQ2tEVoFFbyylGktHllD9hj00iz6kHjEtVzaixsZG1YLLuDk6KIxw==
-----END PUBLIC KEY-----
"""

[keys.walterhpearce]
owner = "@walterhpearce"
public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVwEh3PXPYjpgc40fwl3YqGjWxcKn
fMrJuGb7da6slZ0P28aJ2PvfO7escfLwxNnt8pDp2NX/dGBnIgLzpEP68w==
-----END PUBLIC KEY-----
"""

[keys.online]
online = "gcpkms:projects/rust-tuf/locations/global/keyRings/tufops/cryptoKeys/online/cryptoKeyVersions/1"
public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEurRtI7rt0SeiUzZYtRIazNqugoF1
hd46conktN9SA/x/GioyP9MVC1Rf/lK2VFq1mQo0uXL452CDxz+4iVB0EA==
-----END PUBLIC KEY-----
"""

[roles.root]
keys = ["arlosi"]
threshold = 1
expires_days = 7
signing_days = 3

[roles.targets]
keys = ["arlosi"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.snapshot]
keys = ["online"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.timestamp]
keys = ["online"]
threshold = 1
expires_days = 2
signing_days = 1

[roles.rustup]
keys = ["arlosi"]
paths = ["rustup/"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.channels-stable]
keys = ["online"]
paths = ["channels/stable/"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.channels-beta]
keys = ["online"]
paths = ["channels/beta/"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.channels-nightly]
keys = ["online"]
paths = ["channels/nightly/"]
threshold = 1
expires_days = 365
signing_days = 60

[roles.channels-current]
keys = ["online"]
paths = ["channels/current/"]
threshold = 1
expires_days = 365
signing_days = 60